export const VIEWPORT = Object.freeze({
  width: 1280,
  height: 720,
});

function point(x, z) {
  return Object.freeze({ x, z });
}

function zone(minX, maxX, minZ, maxZ, surfaceType, depth, kind = "island") {
  return Object.freeze({
    minX,
    maxX,
    minZ,
    maxZ,
    surfaceType,
    depth,
    kind,
  });
}

function createLayout({ start, key, gate, exit, frontZones, backZones, gateZone }) {
  return Object.freeze({
    start,
    key,
    gate,
    exit,
    frontZones: Object.freeze(frontZones),
    backZones: Object.freeze(backZones),
    gateZone,
  });
}

function pathProgress(layout, point) {
  const pathX = layout.exit.x - layout.start.x;
  const pathZ = layout.exit.z - layout.start.z;
  return (point.x - layout.start.x) * pathX + (point.z - layout.start.z) * pathZ;
}

function assertKeyBeforeGate(id, layout) {
  if (pathProgress(layout, layout.key) >= pathProgress(layout, layout.gate)) {
    throw new Error(`${id} must place the key before the gate along the main path.`);
  }
}

function createArea({
  id,
  label,
  description,
  keyHint,
  gateHint,
  clearHint,
  rewardText,
  theme,
  layout,
  enemyHealth,
  enemyDamage,
  enemySpeed,
  enemyAggroRange,
  enemyAttackRange,
  frontEnemySpawns,
  backEnemySpawns,
}) {
  assertKeyBeforeGate(id, layout);

  return Object.freeze({
    id,
    label,
    description,
    keyHint,
    gateHint,
    clearHint,
    rewardText,
    theme: Object.freeze(theme),
    layout,
    enemyHealth,
    enemyDamage,
    enemySpeed,
    enemyAggroRange,
    enemyAttackRange,
    frontEnemySpawns: Object.freeze(frontEnemySpawns),
    backEnemySpawns: Object.freeze(backEnemySpawns),
  });
}

export const CHARACTER_DEFS = Object.freeze({
  dragon: {
    id: "dragon",
    name: "Spyro-Style Drake",
    title: "Purple Flame Dragon",
    cost: 0,
    form: "dragon",
    color: "#6d46c7",
    secondaryColor: "#cf7b2e",
    accent: "#f1c85d",
    detailColor: "#efb24d",
    eyeColor: "#8ff6a7",
    description: "Fast all-rounder with sweeping melee and a reliable fire orb.",
    rewardText: "Drake reward: +1 basic damage and +0.04 movement speed.",
    areaReward: {
      basicDamage: 1,
      speed: 0.04,
    },
    maxHealth: 98,
    speed: 8.6,
    jumpStrength: 11.7,
    basicAttack: {
      name: "Wing Slash",
      pattern: "double",
      spreadDegrees: 42,
      cooldown: 0.34,
      damage: 18,
      range: 3.5,
      radius: 2.9,
      arcDegrees: 78,
      color: "#9ceeff",
    },
    special: {
      name: "Flame Orb",
      type: "projectile",
      cooldown: 3.1,
      damage: 32,
      radius: 0.5,
      speed: 18,
      distance: 20,
      pierce: 1,
      color: "#ff9554",
    },
  },
  reef: {
    id: "reef",
    name: "Lagoon Lancer",
    title: "Harpoon Scout",
    cost: 30,
    form: "shark",
    color: "#3c97aa",
    secondaryColor: "#c6e7f1",
    accent: "#5a6570",
    detailColor: "#f0cf6a",
    eyeColor: "#ffd45d",
    description: "Sturdy mid-range hunter with a broad sweep and water shot.",
    rewardText: "Lagoon reward: +4 max health, +1 special damage, and a small heal.",
    areaReward: {
      maxHealth: 4,
      specialDamage: 1,
      heal: 6,
    },
    maxHealth: 114,
    speed: 7.8,
    jumpStrength: 10.9,
    basicAttack: {
      name: "Harpoon Sweep",
      pattern: "stab",
      cooldown: 0.4,
      damage: 20,
      range: 3.9,
      radius: 3.2,
      arcDegrees: 44,
      color: "#8fe8ff",
    },
    special: {
      name: "Tidal Shot",
      type: "projectile",
      count: 3,
      spreadDegrees: 28,
      cooldown: 3.5,
      damage: 24,
      radius: 0.52,
      speed: 16,
      distance: 18,
      color: "#73efff",
    },
  },
  titan: {
    id: "titan",
    name: "Magma Mauler",
    title: "Lava Bruiser",
    cost: 60,
    form: "brute",
    color: "#cf5031",
    secondaryColor: "#7b291d",
    accent: "#ffbf55",
    detailColor: "#ffd26a",
    eyeColor: "#fff3c0",
    description: "Heavy brawler with the hardest hits and a room-clearing slam.",
    rewardText: "Magma reward: +5 max health, +2 slam damage, and a bigger heal.",
    areaReward: {
      maxHealth: 5,
      specialDamage: 2,
      heal: 8,
    },
    maxHealth: 134,
    speed: 7.05,
    jumpStrength: 10.2,
    basicAttack: {
      name: "Gauntlet Crush",
      pattern: "spin",
      cooldown: 0.52,
      damage: 24,
      range: 3.2,
      radius: 3.4,
      arcDegrees: 88,
      color: "#ffe099",
    },
    special: {
      name: "Rune Slam",
      type: "slam",
      rings: 2,
      cooldown: 4.2,
      damage: 42,
      radius: 5.4,
      color: "#8ff6de",
    },
  },
  gale: {
    id: "gale",
    name: "Stormwing Ace",
    title: "Sky Raider",
    cost: 85,
    form: "dragon",
    color: "#2a87d7",
    secondaryColor: "#d9f4ff",
    accent: "#ffe596",
    detailColor: "#8bd6ff",
    eyeColor: "#f8fdff",
    description: "A glass-cannon flier built around speed, reach, and quick cooldowns.",
    rewardText: "Stormwing reward: +1 basic damage and +0.05 movement speed.",
    areaReward: {
      basicDamage: 1,
      speed: 0.05,
    },
    maxHealth: 88,
    speed: 9.4,
    jumpStrength: 12.2,
    basicAttack: {
      name: "Gale Cut",
      pattern: "double",
      spreadDegrees: 56,
      cooldown: 0.3,
      damage: 16,
      range: 3.9,
      radius: 2.6,
      arcDegrees: 64,
      color: "#bdf9ff",
    },
    special: {
      name: "Sky Bolt",
      type: "projectile",
      count: 2,
      spreadDegrees: 16,
      cooldown: 2.6,
      damage: 20,
      radius: 0.48,
      speed: 22,
      distance: 23,
      color: "#d7fbff",
    },
  },
  hex: {
    id: "hex",
    name: "Midnight Gearguard",
    title: "Clocktower Sentinel",
    cost: 115,
    form: "brute",
    color: "#5d4b97",
    secondaryColor: "#231a40",
    accent: "#9de4ff",
    detailColor: "#c9a0ff",
    eyeColor: "#9df7ff",
    description: "A deliberate control hero with a huge arc and punishing burst damage.",
    rewardText: "Gearguard reward: +4 max health and +2 special damage.",
    areaReward: {
      maxHealth: 4,
      specialDamage: 2,
      heal: 4,
    },
    maxHealth: 120,
    speed: 7.4,
    jumpStrength: 10.8,
    basicAttack: {
      name: "Cog Cleave",
      pattern: "spin",
      cooldown: 0.46,
      damage: 22,
      range: 3.6,
      radius: 3.5,
      arcDegrees: 102,
      color: "#c6e8ff",
    },
    special: {
      name: "Phantom Burst",
      type: "burst",
      count: 8,
      cooldown: 3.4,
      damage: 18,
      radius: 0.46,
      speed: 14,
      distance: 12,
      color: "#7ed8ff",
    },
  },
  frost: {
    id: "frost",
    name: "Frost Fang Raider",
    title: "Tundra Hunter",
    cost: 145,
    form: "shark",
    color: "#7ec9f2",
    secondaryColor: "#eff9ff",
    accent: "#5f8fb3",
    detailColor: "#bde7ff",
    eyeColor: "#f7ffff",
    description: "Balanced finisher with reliable knockback and a heavy icy shot.",
    rewardText: "Frostfang reward: +3 max health, +1 basic damage, and a heal.",
    areaReward: {
      maxHealth: 3,
      basicDamage: 1,
      heal: 6,
    },
    maxHealth: 108,
    speed: 8.2,
    jumpStrength: 11.2,
    basicAttack: {
      name: "Icebreaker Sweep",
      cooldown: 0.38,
      damage: 19,
      range: 3.7,
      radius: 3.1,
      arcDegrees: 84,
      color: "#e3fbff",
    },
    special: {
      name: "Glacier Shot",
      type: "projectile",
      cooldown: 3.3,
      damage: 38,
      radius: 0.68,
      speed: 17,
      distance: 19,
      pierce: 2,
      color: "#baf7ff",
    },
  },
  ember: {
    id: "ember",
    name: "Emberflare Glider",
    title: "Solar Firestarter",
    cost: 175,
    form: "dragon",
    color: "#f27a2e",
    secondaryColor: "#ffd15c",
    accent: "#fff2a8",
    detailColor: "#c43c28",
    eyeColor: "#fff7cf",
    description: "A nimble dragon with scorching reach and a fast piercing fire shot.",
    rewardText: "Emberflare reward: +1 basic damage, +1 special damage, and a small heal.",
    areaReward: {
      basicDamage: 1,
      specialDamage: 1,
      heal: 5,
    },
    maxHealth: 94,
    speed: 9.1,
    jumpStrength: 12,
    basicAttack: {
      name: "Solar Swipe",
      pattern: "double",
      spreadDegrees: 32,
      cooldown: 0.32,
      damage: 18,
      range: 4,
      radius: 2.8,
      arcDegrees: 72,
      color: "#ffe194",
    },
    special: {
      name: "Sunspike",
      type: "projectile",
      count: 5,
      spreadDegrees: 36,
      cooldown: 2.8,
      damage: 16,
      radius: 0.42,
      speed: 21,
      distance: 22,
      color: "#ffbd55",
    },
  },
  terra: {
    id: "terra",
    name: "Terra Thornback",
    title: "Rootbound Guardian",
    cost: 205,
    form: "brute",
    color: "#5f9a4f",
    secondaryColor: "#36552f",
    accent: "#f0d77a",
    detailColor: "#a86f42",
    eyeColor: "#d9ffd3",
    description: "A tough guardian with sweeping thorn strikes and a huge earth slam.",
    rewardText: "Terra reward: +6 max health and +1 basic damage.",
    areaReward: {
      maxHealth: 6,
      basicDamage: 1,
      heal: 7,
    },
    maxHealth: 142,
    speed: 6.9,
    jumpStrength: 10,
    basicAttack: {
      name: "Thorn Knuckle",
      pattern: "spin",
      cooldown: 0.5,
      damage: 25,
      range: 3.4,
      radius: 3.6,
      arcDegrees: 96,
      color: "#d9ff9a",
    },
    special: {
      name: "Rootquake",
      type: "slam",
      rings: 3,
      cooldown: 4.4,
      damage: 46,
      radius: 5.8,
      color: "#c8ff8d",
    },
  },
  volt: {
    id: "volt",
    name: "Voltfin Striker",
    title: "Lightning Reef Duelist",
    cost: 240,
    form: "shark",
    color: "#285bd8",
    secondaryColor: "#f5fbff",
    accent: "#ffec5f",
    detailColor: "#74dcff",
    eyeColor: "#fff6a8",
    description: "A quick reef fighter with snappy cooldowns and electric burst shots.",
    rewardText: "Voltfin reward: +0.05 movement speed, +2 special damage, and a small heal.",
    areaReward: {
      speed: 0.05,
      specialDamage: 2,
      heal: 5,
    },
    maxHealth: 104,
    speed: 8.7,
    jumpStrength: 11.4,
    basicAttack: {
      name: "Static Spear",
      pattern: "stab",
      cooldown: 0.35,
      damage: 20,
      range: 3.8,
      radius: 3,
      arcDegrees: 38,
      color: "#f7ff91",
    },
    special: {
      name: "Storm Harpoon",
      type: "projectile",
      count: 3,
      spreadDegrees: 18,
      cooldown: 2.9,
      damage: 22,
      radius: 0.46,
      speed: 20,
      distance: 21,
      pierce: 1,
      color: "#f9ff6f",
    },
  },
  klins: {
    id: "klins",
    name: "Mr Klins",
    title: "Keyboard Commander",
    cost: 275,
    form: "teacher",
    color: "#8f9aa7",
    secondaryColor: "#2d3440",
    accent: "#f4f7fb",
    detailColor: "#c88762",
    eyeColor: "#95d4ff",
    description: "A goofy keyboard-swinging hero with fast bonks and a spray of keycaps.",
    rewardText: "Mr Klins reward: +1 basic damage, +0.04 movement speed, and a small heal.",
    areaReward: {
      basicDamage: 1,
      speed: 0.04,
      heal: 5,
    },
    maxHealth: 110,
    speed: 8.4,
    jumpStrength: 11.1,
    basicAttack: {
      name: "Keyboard Bonk",
      pattern: "double",
      spreadDegrees: 26,
      cooldown: 0.36,
      damage: 21,
      range: 3.8,
      radius: 3,
      arcDegrees: 82,
      color: "#f4f7fb",
    },
    special: {
      name: "Keycap Scatter",
      type: "projectile",
      count: 6,
      spreadDegrees: 44,
      cooldown: 3,
      damage: 15,
      radius: 0.38,
      speed: 20,
      distance: 19,
      pierce: 1,
      color: "#d7ecff",
    },
  },
});

export const CHARACTER_LIST = Object.freeze(Object.values(CHARACTER_DEFS));

const CRYSTAL_CAVERNS = createArea({
  id: "crystal-caverns",
  label: "Crystal Caverns",
  description: "Deep underground, ancient crystals hum around broken mine tracks.",
  keyHint: "Search the upper crystal ledge and take the cavern key.",
  gateHint: "Bring the key back to the mine gate in the center hall.",
  clearHint: "Defeat the cave guards, then enter the restored crystal portal.",
  rewardText: "Crystal Caverns cleared. The cave portal sings back to life.",
  theme: {
    biome: "crystal",
    sky: "#76d9ff",
    fog: "#d9fbff",
    sun: "#fff0a8",
    sunIntensity: 1.34,
    hemiIntensity: 1.08,
    fogNear: 38,
    fogFar: 148,
    grass: "#5dbf58",
    grassDark: "#2d7c36",
    sand: "#f0dc94",
    cliff: "#8d6a3d",
    cliffDark: "#4f321b",
    stone: "#b7b8a6",
    stoneDark: "#686f64",
    wood: "#73553d",
    woodDark: "#402917",
    metal: "#cfdcff",
    metalDark: "#5a658b",
    ice: "#9cf7ff",
    iceDark: "#5790a8",
    water: "#14a9dd",
    waterOpacity: 0.82,
    shimmerOpacity: 0.16,
    portal: "#8ef3ff",
    crystal: "#f8df68",
    gate: "#e7c56f",
    enemy: "#bfff5a",
    enemyDark: "#4d7a19",
    backdropSurfaceType: "crystal",
  },
  layout: createLayout({
    start: point(0, 44),
    key: point(14, 16),
    gate: point(0, 6),
    exit: point(0, -48),
    frontZones: [
      zone(-18, 18, 34, 52, "crystal", 6.2, "island"),
      zone(-5, 5, 18, 36, "stone", 3.8, "bridge"),
      zone(-20, 20, 4, 22, "crystal", 6.8, "island"),
      zone(8, 16, -2, 12, "wood", 3.6, "bridge"),
      zone(12, 30, -10, 8, "crystal", 6.1, "island"),
    ],
    backZones: [
      zone(-14, 14, -18, 10, "crystal", 6.3, "island"),
      zone(-4, 4, -38, -16, "wood", 3.6, "bridge"),
      zone(-18, 18, -60, -36, "crystal", 6.9, "island"),
    ],
    gateZone: zone(-6, 6, -2, 12, "stone", 3.9, "bridge"),
  }),
  enemyHealth: 52,
  enemyDamage: 10,
  enemySpeed: 4.9,
  enemyAggroRange: 18,
  enemyAttackRange: 2.35,
  frontEnemySpawns: [
    point(-10, 46),
    point(11, 40),
    point(-12, 13),
    point(5, 8),
    point(22, -1),
    point(15, 6),
  ],
  backEnemySpawns: [
    point(-8, -7),
    point(8, 2),
    point(0, -22),
    point(-12, -45),
    point(10, -44),
    point(11, -54),
  ],
});

const VOLCANO_VALLEY = createArea({
  id: "volcano-valley",
  label: "Volcano Valley",
  description: "Molten rivers cut through basalt islands and a lava engine churns ahead.",
  keyHint: "Push through the forge path and steal the engine key from the lava deck.",
  gateHint: "Carry the key back across the heat bridge to unlock the magma lock.",
  clearHint: "Wipe out the eruption guards and step into the cooled portal ring.",
  rewardText: "Volcano Valley cleared. The lava flow settles into a safe crossing.",
  theme: {
    biome: "volcano",
    sky: "#472018",
    fog: "#ffbe83",
    sun: "#ffcf8a",
    sunIntensity: 1.28,
    hemiIntensity: 0.94,
    fogNear: 32,
    fogFar: 118,
    grass: "#776556",
    grassDark: "#44352a",
    sand: "#8e6b58",
    cliff: "#6f4c39",
    cliffDark: "#362016",
    stone: "#6b5b55",
    stoneDark: "#302726",
    wood: "#7b4a29",
    woodDark: "#43200d",
    metal: "#d2a06a",
    metalDark: "#684027",
    ice: "#ffa76b",
    iceDark: "#8d3922",
    water: "#ff621f",
    waterOpacity: 0.86,
    shimmerOpacity: 0.1,
    portal: "#ffd07c",
    crystal: "#ff9449",
    gate: "#ffbf6c",
    enemy: "#69f4ff",
    enemyDark: "#1f6671",
    backdropSurfaceType: "volcanic",
  },
  layout: createLayout({
    start: point(-18, 44),
    key: point(-12, 14),
    gate: point(-4, 6),
    exit: point(12, -48),
    frontZones: [
      zone(-30, -8, 34, 52, "volcanic", 6, "island"),
      zone(-22, -12, 18, 36, "stone", 3.6, "bridge"),
      zone(-30, -4, 6, 22, "volcanic", 6.4, "island"),
      zone(-8, 4, 0, 12, "stone", 3.6, "bridge"),
      zone(4, 28, -16, 8, "volcanic", 5.8, "island"),
    ],
    backZones: [
      zone(-18, 8, -20, 8, "volcanic", 6, "island"),
      zone(0, 14, -38, -18, "stone", 3.6, "bridge"),
      zone(-4, 28, -60, -36, "volcanic", 6.6, "island"),
    ],
    gateZone: zone(-10, 0, 0, 12, "stone", 3.7, "bridge"),
  }),
  enemyHealth: 62,
  enemyDamage: 11,
  enemySpeed: 5,
  enemyAggroRange: 18,
  enemyAttackRange: 2.4,
  frontEnemySpawns: [
    point(-24, 44),
    point(-13, 36),
    point(-22, 12),
    point(-6, 8),
    point(18, -8),
    point(9, -3),
  ],
  backEnemySpawns: [
    point(-10, -4),
    point(2, 3),
    point(7, -27),
    point(6, -48),
    point(20, -43),
    point(15, -56),
  ],
});

const SKY_PIRATE_FORTRESS = createArea({
  id: "sky-pirate-fortress",
  label: "Sky Pirate Fortress",
  description: "Floating decks, chained catwalks, and pirate cannons fill the sky route.",
  keyHint: "Break into the brig deck on the right and grab the captive key.",
  gateHint: "Return to the main chain lock and open the rear command route.",
  clearHint: "Clear the command deck, then jump into the air portal beyond it.",
  rewardText: "Sky Pirate Fortress cleared. The cloud lane opens to the next island.",
  theme: {
    biome: "skyfort",
    sky: "#8fd6ff",
    fog: "#ebfbff",
    sun: "#fff4b1",
    sunIntensity: 1.4,
    hemiIntensity: 1.12,
    fogNear: 46,
    fogFar: 150,
    grass: "#77c06a",
    grassDark: "#3d7e38",
    sand: "#d8c093",
    cliff: "#86674c",
    cliffDark: "#553722",
    stone: "#a2a6bd",
    stoneDark: "#54596f",
    wood: "#8a5f37",
    woodDark: "#54341a",
    metal: "#c6d0ea",
    metalDark: "#53617f",
    ice: "#90f0ff",
    iceDark: "#46849d",
    water: "#b7e8ff",
    waterOpacity: 0.66,
    shimmerOpacity: 0.14,
    portal: "#8de9ff",
    crystal: "#78cfff",
    gate: "#e1c78e",
    enemy: "#ff734b",
    enemyDark: "#7a2d18",
    backdropSurfaceType: "deck",
  },
  layout: createLayout({
    start: point(0, 46),
    key: point(12, 18),
    gate: point(0, 8),
    exit: point(0, -50),
    frontZones: [
      zone(-14, 14, 38, 54, "deck", 5.4, "island"),
      zone(-6, 6, 22, 40, "metal", 3.4, "bridge"),
      zone(-18, 18, 10, 28, "deck", 5.8, "island"),
      zone(10, 20, -2, 14, "wood", 3.4, "bridge"),
      zone(18, 36, -14, 8, "deck", 5.6, "island"),
    ],
    backZones: [
      zone(-12, 12, -18, 8, "deck", 5.8, "island"),
      zone(-6, 6, -38, -16, "metal", 3.6, "bridge"),
      zone(-18, 18, -60, -34, "deck", 6.1, "island"),
    ],
    gateZone: zone(-4, 4, 4, 12, "metal", 3.6, "bridge"),
  }),
  enemyHealth: 72,
  enemyDamage: 12,
  enemySpeed: 5.2,
  enemyAggroRange: 19,
  enemyAttackRange: 2.45,
  frontEnemySpawns: [
    point(-8, 47),
    point(7, 42),
    point(-10, 18),
    point(6, 14),
    point(28, -5),
    point(21, 3),
  ],
  backEnemySpawns: [
    point(-8, -8),
    point(5, -3),
    point(0, -28),
    point(-10, -48),
    point(11, -44),
    point(9, -57),
  ],
});

const HAUNTED_CLOCKTOWER = createArea({
  id: "haunted-clocktower",
  label: "Haunted Clocktower",
  description: "Twisted halls, broken time gears, and cursed lanterns rule the tower.",
  keyHint: "Climb through the crooked gear hall and recover the lost time gear.",
  gateHint: "Return the gear to the clock lock near the middle landing.",
  clearHint: "Defeat the phantoms in the upper tower and enter the midnight portal.",
  rewardText: "Haunted Clocktower cleared. Time steadies and the next path appears.",
  theme: {
    biome: "haunted",
    sky: "#261845",
    fog: "#9d88e2",
    sun: "#d6c8ff",
    sunIntensity: 0.92,
    hemiIntensity: 0.82,
    fogNear: 28,
    fogFar: 110,
    grass: "#6557a9",
    grassDark: "#37276c",
    sand: "#73629c",
    cliff: "#4a3a75",
    cliffDark: "#1e1736",
    stone: "#7e76ad",
    stoneDark: "#40395f",
    wood: "#6e4d3a",
    woodDark: "#392516",
    metal: "#b9b0dd",
    metalDark: "#5a527a",
    ice: "#84dfff",
    iceDark: "#37607e",
    water: "#371e61",
    waterOpacity: 0.8,
    shimmerOpacity: 0.07,
    portal: "#a9e7ff",
    crystal: "#c58cff",
    gate: "#d4b5ff",
    enemy: "#8cff63",
    enemyDark: "#2d6b20",
    backdropSurfaceType: "haunted",
  },
  layout: createLayout({
    start: point(-18, 44),
    key: point(8, 18),
    gate: point(4, 8),
    exit: point(-12, -48),
    frontZones: [
      zone(-30, -8, 34, 52, "haunted", 6, "island"),
      zone(-18, -8, 18, 36, "stone", 3.8, "bridge"),
      zone(-10, 16, 6, 24, "haunted", 6.2, "island"),
      zone(10, 20, -4, 12, "wood", 3.7, "bridge"),
      zone(12, 30, -16, 6, "haunted", 6.4, "island"),
    ],
    backZones: [
      zone(-14, 12, -20, 6, "haunted", 6.1, "island"),
      zone(-6, 6, -38, -18, "stone", 3.7, "bridge"),
      zone(-26, 0, -60, -34, "haunted", 6.7, "island"),
    ],
    gateZone: zone(-2, 10, 4, 12, "stone", 3.9, "bridge"),
  }),
  enemyHealth: 82,
  enemyDamage: 13,
  enemySpeed: 5.35,
  enemyAggroRange: 19,
  enemyAttackRange: 2.5,
  frontEnemySpawns: [
    point(-22, 46),
    point(-12, 30),
    point(0, 16),
    point(13, 8),
    point(22, -6),
    point(18, 2),
  ],
  backEnemySpawns: [
    point(-8, -6),
    point(6, 0),
    point(0, -28),
    point(-18, -48),
    point(-6, -40),
    point(-14, -56),
  ],
});

const FROZEN_FANG_TUNDRA = createArea({
  id: "frozen-fang-tundra",
  label: "Frozen Fang Tundra",
  description: "Icy ruins, frozen bridges, and a storm-bitten citadel await ahead.",
  keyHint: "Cross the rune shelf and claim the frost seal from the far ridge.",
  gateHint: "Carry the seal to the frozen gate and unlock the last stretch.",
  clearHint: "Break the final ambush at the citadel, then enter the aurora portal.",
  rewardText: "Frozen Fang Tundra cleared. The blizzard parts around the portal.",
  theme: {
    biome: "frozen",
    sky: "#9fd4ff",
    fog: "#eff8ff",
    sun: "#f6fcff",
    sunIntensity: 1.22,
    hemiIntensity: 1.08,
    fogNear: 38,
    fogFar: 145,
    grass: "#b0d9f3",
    grassDark: "#6c97b4",
    sand: "#eaf5ff",
    cliff: "#83a8c4",
    cliffDark: "#49677f",
    stone: "#c2d6e6",
    stoneDark: "#6f879d",
    wood: "#7f6a56",
    woodDark: "#4a3b2f",
    metal: "#d9ebff",
    metalDark: "#6d89a7",
    ice: "#9be7ff",
    iceDark: "#5592b1",
    water: "#8edaff",
    waterOpacity: 0.76,
    shimmerOpacity: 0.16,
    portal: "#dbf7ff",
    crystal: "#bdf8ff",
    gate: "#dff1ff",
    enemy: "#d48cff",
    enemyDark: "#60308d",
    backdropSurfaceType: "ice",
  },
  layout: createLayout({
    start: point(0, 46),
    key: point(-12, 16),
    gate: point(0, 6),
    exit: point(0, -52),
    frontZones: [
      zone(-20, 20, 36, 54, "ice", 6.1, "island"),
      zone(-6, 6, 20, 38, "ice", 3.6, "bridge"),
      zone(-18, 18, 6, 24, "ice", 6.4, "island"),
      zone(-22, -10, -4, 10, "ice", 3.6, "bridge"),
      zone(-36, -16, -18, 4, "ice", 6, "island"),
    ],
    backZones: [
      zone(-10, 10, -22, 6, "ice", 6.3, "island"),
      zone(-4, 4, -40, -20, "ice", 3.7, "bridge"),
      zone(-22, 22, -64, -38, "ice", 6.8, "island"),
    ],
    gateZone: zone(-4, 4, 0, 12, "ice", 3.8, "bridge"),
  }),
  enemyHealth: 94,
  enemyDamage: 14,
  enemySpeed: 5.5,
  enemyAggroRange: 20,
  enemyAttackRange: 2.55,
  frontEnemySpawns: [
    point(0, 48),
    point(10, 40),
    point(-8, 14),
    point(-18, 4),
    point(-27, -8),
    point(-20, -13),
  ],
  backEnemySpawns: [
    point(-6, -6),
    point(6, 2),
    point(0, -28),
    point(-12, -50),
    point(12, -46),
    point(16, -58),
  ],
});

const AREAS = Object.freeze([
  CRYSTAL_CAVERNS,
  VOLCANO_VALLEY,
  SKY_PIRATE_FORTRESS,
  HAUNTED_CLOCKTOWER,
  FROZEN_FANG_TUNDRA,
]);

export const TOTAL_AREAS = AREAS.length;

export function getAreaConfig(areaIndex) {
  return AREAS[Math.max(0, Math.min(areaIndex, AREAS.length - 1))];
}
